spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    view-names: th/*
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    generate-ddl: off
    database: mysql

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/boardProjectJpa?characterEncoding=UTF-8
    username: root
    password: 1234


server:
  port: 8080

logging:
  file:
    path: logback-spring