spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    view-names: th/*
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/boardProject
    username: root
    password: 1234

server:
  port: 8080

logging:
  file:
    path: logback-spring